name: Unit tests, TODOs to issues and linting 🧪

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: pip install -r requirements.txt
      - name: "Run tests with coverage"
        run: pytest -vv --cov=src 
  
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Super-Linter
        uses: super-linter/super-linter/slim@v7.1.0

  todos-to-issue:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Convert TODOs to Issues"
        uses: "alstr/todo-to-issue-action@v5"